#!/usr/bin/env python3
"""Generate src/names.h: a flash-resident national-dex name table.

Fetches every species name from PokéAPI (ordered by dex id) and emits a
PROGMEM-friendly C array indexed by (id - 1). Names are display-cased
("mr-mime" -> "Mr. Mime", "nidoran-f" -> "Nidoran F").

Usage:  python3 tools/gen_names.py            # writes src/names.h
Re-run whenever you want to refresh the list (e.g. new generations).
"""
import json
import os
import sys
import urllib.request

COUNT_URL = "https://pokeapi.co/api/v2/pokemon-species?limit=100000&offset=0"
OUT = os.path.join(os.path.dirname(__file__), "..", "src", "names.h")

# A few names that read better with explicit punctuation than plain title-case.
SPECIAL = {
    "mr-mime": "Mr. Mime",
    "mime-jr": "Mime Jr.",
    "mr-rime": "Mr. Rime",
    "type-null": "Type: Null",
    "ho-oh": "Ho-Oh",
    "porygon-z": "Porygon-Z",
    "jangmo-o": "Jangmo-o",
    "hakamo-o": "Hakamo-o",
    "kommo-o": "Kommo-o",
    "nidoran-f": "Nidoran F",
    "nidoran-m": "Nidoran M",
    "farfetchd": "Farfetch'd",
    "sirfetchd": "Sirfetch'd",
    "flabebe": "Flabébé",
}


def display_name(slug: str) -> str:
    if slug in SPECIAL:
        return SPECIAL[slug]
    return " ".join(w.capitalize() for w in slug.split("-"))


def main() -> int:
    req = urllib.request.Request(COUNT_URL, headers={"User-Agent": "pokedex-display-gen/1.0"})
    with urllib.request.urlopen(req, timeout=30) as r:
        data = json.load(r)
    results = data["results"]  # already dex-ordered
    names = [display_name(item["name"]) for item in results]

    lines = [
        "#pragma once",
        "// AUTO-GENERATED by tools/gen_names.py — do not edit by hand.",
        f"// National dex names, indexed by (id - 1). Count = {len(names)}.",
        "#include <pgmspace.h>",
        "",
        f"#define DEX_NAME_COUNT {len(names)}",
        "",
        "static const char* const DEX_NAMES[] PROGMEM = {",
    ]
    for i, n in enumerate(names, start=1):
        esc = n.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'    "{esc}",  // {i}')
    lines.append("};")
    lines.append("")

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"Wrote {len(names)} names to {os.path.normpath(OUT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
